# -- Libraries
library(directlabels)
library(shinyWidgets)
library(shinythemes)
library(excessmort)
library(lubridate)
library(tidyverse)
# library(gridExtra)
library(shinyjs)
library(scales)
library(DT)
# library(sf)
source("theme_sandstone.R")
my_palette <- c("#252525", "#cb181d", "#2171b5", "#6a51a3", "#238b45", "#6a51a3")